language: c
before_install:
    - sudo apt-get install -y cmake zlib1g-dev git libpng16-dev nasm
compiler:
    - clang
    - gcc
script: mkdir build && cd build && cmake -G"Unix Makefiles" -DPNG_SUPPORTED=TRUE ../ && make SHARED=0 CC='gcc -static' && make install

