language: c
os: linux
dist: bionic
before_install:
    - sudo apt-get update -y && sudo apt-get install -y cmake zlib1g-dev libpng-dev git nasm
compiler:
    - clang
    - gcc
script: mkdir build && cd build && cmake -G"Unix Makefiles" -DPNG_SUPPORTED=TRUE ../ && make SHARED=0 CC='gcc -static' && make install

