language: c
os: linux
before_install:
    - sudo apt-get install -y cmake zlib1g-dev libpng12-dev git nasm
compiler:
    - clang
    - gcc
script: cmake -G"Unix Makefiles" . && make SHARED=0 CC='gcc -static' && make test

