language: c
os: linux
before_install:
    - sudo apt-get install -y cmake zlib1g-dev libpng-dev git cmake nasm
    - mkdir build && cd build
compiler:
    - clang
    - gcc
script: mkdir build && cd build && cmake -G"Unix Makefiles" ../ && make SHARED=0 CC='gcc -static' && make test

